imports:
    - { resource: ../inputs.yaml }
    - { resource: ../outputs.yaml }
    - { resource: ../rules.yaml }

services:
    _defaults:
        autowire: true
        autoconfigure: true
        bind:
            $kernelProjectDir: '%kernel.project_dir%'
            $inputs: '%inputs%'
            $outputs: '%outputs%'
            $rules: '%rules%'
            $serializer: '@serializer'

    App\Controller\:
        resource: '../src/Controller'
        tags: ['controller.service_arguments']

    App\Command\:
        resource: '../src/Command'
        public: true

    App\Manager\:
        resource: '../src/Manager'

    App\Factory\:
        resource: '../src/Factory'

    App\SubRoutine\:
        resource: '../src/SubRoutine'
